### ISSUE TITLE
option to start with a blank (black) screen

### ISSUE THREAD

**Issue by mcanepa** [Rezmason/matrix#18]
First of all, this is fantastic! great job!!! and thanks for sharing it and the detail explanations you give on every issue.

Maybe I have missed some configuration option, but if there isn't it would be great for the code to start raining from the top like the opening titles. Right now when the code starts is already all over the screen.

**Comment by Rezmason** [comment]
Thank you for your interest and your kind words!You're absolutely right— at the moment there's no mode to begin with a blank screen. I had an idea for how to add that this morning, actually, and I'll give it a try in a couple days.On Sep 21, 2022 6:15 PM, Matías Cánepa ***@***.***> wrote:
First of all, this is fantastic! great job!!! and thanks for sharing it and the detail explanations you give on every issue.
Maybe I have missed some configuration option, but if there isn't it would be great for the code to start raining from the top like the opening titles. Right now when the code starts is already all over the screen.

**Comment by Rezmason** [comment]
[Here's what I came up with](https://rezmason.github.io/matrix/?skipIntro=false), feedback welcome! Thanks again for the suggestion.

**Comment by avidrucker** [comment]
@Rezmason Please forgive the post on an already closed issue, but it appears that the screen does not start out completely blank/black for me on https://rezmason.github.io/matrix/?skipIntro=false - instead it starts with glowing blocks of code. I am using the Chrome browser for Linux. Is there a way to turn these off these glowing blocks as well to start from a completely black/empty background? Please let me know if you'd rather I make a new issue.

![image](https://github.com/Rezmason/matrix/assets/6962664/4d8de356-9b5c-423c-84f5-6ea2fb02865d)

**Comment by Rezmason** [comment]
@avidrucker That's incredible. There are people that want this to be able to intentionally happen and I'm kind of one of them. The bug is an artist. Also, it's a bug in Chrome, but that won't stop me from addressing it here.

If I had to guess, the textures that store the rain aren't properly blanked in Chrome. If so, you should be able to see the blocks in this screenshot slowly giving way to normal matrix rain, from the top of the screen downward. Can you confirm?

To fix this— this is a note for my future self— there should probably be some blank data passed into `makeDoubleBuffer` on [line 19](https://github.com/Rezmason/matrix/blob/master/js/regl/rainPass.js#L19) of the `rainPass`.

**Comment by Rezmason** [comment]
Repro'd in Chrome on Macintosh

**Comment by avidrucker** [comment]
It appears fixed for me (starting out from a black/blank screen now), and I greatly appreciate you doing this! That said, I feel kinda sad that you like the "blocky remnants" effect yet still took it out. I agree that the bug is an artist :smile:  Perhaps you might bring it back as an intentional setting? Either way, thank you again.

**Comment by Rezmason** [comment]
That's exactly what I'll do, after I do the dozen other things I've said I would in the project this year 😆 thanks for giving me an easy accomplishment, it honestly helps to build my momentum
