### ISSUE TITLE
Extra Classic version

### ISSUE THREAD

**Issue by lexum0** [Rezmason/matrix#2]
It feels perfect as Matrix Reloaded code.

How about adding another version, "Classic", reminiscent of the original ones (less 3D) from The Matrix besides "Reloaded" (the one that's named 1999).

**Comment by lexum0** [comment]
If you need a hand let me know if I can be of assistance on anything

**Comment by Rezmason** [comment]
Haven't forgotten about this, just swamped by my new job,, and other similar obligations.

The way I see it, the main differences between the current effect and "classic" are: 

1. Classic code is all one color, except for the "lowest characters on a raindrop", which are white.
1. Classic code's glyphs mostly don't change at all; here and there there are glyphs that change very rapidly
1. Classic code has no ordered glyph cycle, though I'll triple check. I'll probably leave this alone to be honest

**Comment by Rezmason** [comment]
I've named this version "throwback". Feedback appreciated.

[Throwback Matrix](https://rezmason.github.io/matrix/?version=throwback)

I actually feel some nostalgia for this version that I don't feel with "1999"— it's got something to do with how all the glyphs are packed so tightly together, with the 1.5-to-1 size ratio.

**Comment by lexum0** [comment]
Real nice!

I think there's no need to alter the glyphs' size so you can easily switch between them. Switching from 1999 to throwback makes them feel super big like I need to zoom out. It's not a problem since you can very easily change the settings but I would keep the size the same.

**Comment by lexum0** [comment]
I feel the color may be too plain and did a quick search to verify and I think there are different versions of the code in the same movie. Which version did you reference for throwback? 
I found this one https://www.youtube.com/watch?v=3vAnuBtyEYE which seems to me like a mix of 1999 and throwback

**Comment by Rezmason** [comment]
Addressed the sizing issue. Since the original glyphs are stretched taller in the 1999 film, it makes sense to increase the number of columns by that same stretch ratio to keep everything looking equally sized.

My reference was the opening titles, although the coloration of those titles varies from video to video, and from edition to edition. The 4K Blue Ray I have at home renders them as quite anemic! This morning I've tried approximating the bloom ("glow") and color in [this one](https://www.youtube.com/watch?v=kIXNpePYzZU&feature=youtu.be&t=31).

**Comment by Rezmason** [comment]
Final fix to tracer length, which is now governed by "brightnessThreshold".
