### ISSUE TITLE
I would love to see a version from the original 1999 film

### ISSUE THREAD

**Issue by CaseyFueller** [Rezmason/matrix#28]
I believe the one labeled as "Classic Matrix code" is much closer to the sequels. The rain from the original is quite different:
  
https://www.youtube.com/watch?v=BMzYUPx5oXo

**Comment by Rezmason** [comment]
Ah, good eye!

What I think you're looking for is the version I called "[operator](https://rezmason.github.io/matrix/?version=operator)". Some versions also have years as nicknames:

https://rezmason.github.io/matrix/?version=1999
https://rezmason.github.io/matrix/?version=2003
https://rezmason.github.io/matrix/?version=2021

Whether the 1999 version should be called "classic" instead of the 2003 version is debatable and subjective. I think the 2003 version is more familiar to most people because we _collectively misremember_ and overlook some of those idiosyncrasies you and I observe in the 1999 version.

But that version is here for you, chum, whether it's got the right name or not. ☺️ And feedback's always welcome.
