### ISSUE TITLE
Horizontal black stripe with high density

### ISSUE THREAD

**Issue by presianbg** [Rezmason/matrix#33]
Hi,

First and foremost, thank you for the awesome project! 

I've noticed that increasing the density results in a black stripe in the middle of the screen, which becomes more and more noticeable the higher the density is.

This is the [settings](https://rezmason.github.io/matrix/?effect=customStripes&colors=119,0,121,1,1,0,0,1,1&width=100&volumetric=true&forwardSpeed=0.2&density=10&ditherMagnitude=0.02) I've used. 

![image](https://user-images.githubusercontent.com/2163486/193207547-f69dda10-8292-4c6d-affa-34ce98f1bddd.png)

Do you see the same on your end ? 

Cheers,
PY

**Comment by Rezmason** [comment]
Thanks for your interest!

Yep, this line is present at any density, when the `width` is even. When it's odd, it gets hidden:

https://rezmason.github.io/matrix/?effect=customStripes&colors=119,0,121,1,1,0,0,1,1&width=100&volumetric=true&forwardSpeed=0.2&density=10&ditherMagnitude=0.02&width=81

![image](https://user-images.githubusercontent.com/1041555/193208310-250b5a73-e178-44fd-b5b2-eea13bac3e9a.png)

Nice settings by the way!

So, what's going on? Basically, volumetric mode gives the glyph columns unique distances from the camera, but otherwise the glyphs are _still in a grid_. Most of the gaps between rows of glyphs are "above" or "below" the vanishing point; this one is directly aligned with the horizon.

The fix is for me to add a slight, random vertical offset to the  columns in 3D mode, so the grid is shaken up a bit. Let's see how long that takes...

**Comment by Rezmason** [comment]
Fixed! Remember to clear the broken version from your browser cache.
