### ISSUE TITLE
How to use 3D mode?

### ISSUE THREAD

**Issue by meet1919** [Rezmason/matrix#5]
I am new in front-end so I can't execute it properly. Can you  define the steps properly?
I am using django for backend

**Comment by Rezmason** [comment]
Hello! Can you elaborate what help you need?

The structure of this project makes some assumptions that you might want to modify for your own use:
- It assumes it runs alone in the web page
- It assumes it has to manage the resizing of the window
- It assumes that the mode you want is specified in the page's URL

Depending on your goals, you might want to modify the code so some or all of these assumptions are gone.

To test 3D mode, just include `volumetric=true` in the URL's "query string", like so:

[https://rezmason.github.io/matrix/?volumetric=true](https://rezmason.github.io/matrix/?volumetric=true)

This informs the rain render pass to represent the code as 3D objects that are drawn in perspective, rather than being regions of pixels on the screen. Volumetric "3D" mode is great for tricks like 3D perspective, but the default mode is better suited for the radial effect seen in [https://rezmason.github.io/matrix/?version=paradise](this version, for example).

Please clarify if there's more particular help you need.

Regards,

Rezmason
