### ISSUE TITLE
Available to download these animations?

### ISSUE THREAD

**Issue by KarmaBeast** [Rezmason/matrix#60]
Hi there! I was wondering can I somehow download these animations in video format? I'm unable to figure out how to:/

**Comment by antzpantz** [comment]
Screen recorder...

**Comment by Rezmason** [comment]
Hi! This project is a live, dynamic visual effect for the browser. For now, there's no scoped plan to render it to a video file. To capture video footage of it, your best bet is to record your screen like @antzpantz concisely suggested, and edit the footage to your liking.

You might find the `?loops=true` option to be helpful, because it guarantees that the visual effect repeats itself after some amount of time. Then, you can crop your video to that loop and extend it for however long you need the effect to run.

Sorry for the slow reply, I've been having a tough time getting back to this project. 😅
