### ISSUE TITLE
Matrix Resurrections code

### ISSUE THREAD

**Issue by tanar185** [Rezmason/matrix#7]
Where exactly did you get the assets for these? https://raw.githubusercontent.com/Rezmason/matrix/master/assets/resurrections_msdf.png 
Did you generate them yourself from screenshots, or is there a more direct source (like what you claim you found for the original Matrix code from archive)?

Will these be included in the font set?

**Comment by Rezmason** [comment]
Hi there! Good questions. 

If you don't mind, I'll first respond by copying [my explanation on Reddit](https://www.reddit.com/r/matrix/comments/reiylc/finished_all_the_glyphs_in_the_new_matrix_code/):

> I've got the vector outlines of my rendition if you want it, but it is absolutely a sketchy preliminary version, and people who like things to look right when you zoom in may be a bit disappointed.
> 
> The glyphs [in this promo](https://www.youtube.com/watch?v=g1VjShDGelo) occupy a grid. Photoshop lets you import frames from an MP4, export them as individual files, adjust all their levels and then batch-slice them into a grid. That's how I got a folder full of 156,996 22x22-pixel PNGs. With a few other tricks, if you sort them by size you can separate the wheat from the chaff.
> 
> To vectorize them, I skimmed a few suspect Unicode blocks. Fun fact: you can script Fontforge to export all the glyphs in a font as SVGs, which is how I got the folder full of 2,360 vector files. About 75 of these look either exactly like what the VFX folks put in the new code rain, or close enough to spend maybe ten minutes on each glyph.
> 
> I couldn't find the last two rows of symbols, give or take, so I assembled them from pieces of the rest, which is a good first step to how you make a font look consistent.
> 
> So. What are these glyphs?
> 
> The digits, the letter Z, and a bunch of math symbols are from [Chicago](https://en.wikipedia.org/wiki/Chicago_(typeface)), just like the Wachowskis. Simon Whiteley at Animal Logic, who designed the original Matrix glyphs, is commonly quoted as saying the backwards [katakana](https://unicode-table.com/en/blocks/katakana/) that make up the rest of the classic glyphs "came from" a sushi recipe book. They were modified quite a bit. His colleague Lindsay Fleay [recently spoke a bunch more](https://www.reddit.com/r/matrix/comments/q0zx5h/comment/hfbq2oq) about this original creative process. One interesting takeaway is that there were way more glyphs in Whiteley's set, which they pared down to the ones we saw in the original trilogy.
> 
> Now for the new ones.
> 
> You've got your [Buginese](https://unicode-table.com/en/blocks/buginese/), your [Kayah Li](https://unicode-table.com/en/blocks/kayah-li/), a little [Phags Pa](https://unicode-table.com/en/alphabets/phags-pa/) or maybe [Tibetan](https://unicode-table.com/en/alphabets/tibetan/), some [Kannada](https://unicode-table.com/en/blocks/kannada/), some [Mongolian](https://unicode-table.com/en/blocks/mongolian/) _maybe_ in a particular font — my unfamiliarity with these alphabets, their cultures and their fonts is really doing me in here — they might have modified some [Saurashtra](https://unicode-table.com/en/blocks/saurashtra/), but from a font I can't find. The rest of the symbols I rebuilt by hand, more or less, with the trailer glyphs serving as a reference, but I suspect someone who knows more languages than me could identify what I couldn't.
> 
> It's possible that a bunch of these glyphs are from Simon Whiteley's original expanded set. Animal Logic is an Australian studio, and as far as I can tell, all these scripts are from cultures geographically between India, Australia and Japan. On the other hand, they could also be new contributions that reflect the aesthetic decisions (and cultural biases) of the team working on Resurrections. I'd like to try reaching out and asking a VFX artist after the film is released.

**Comment by Rezmason** [comment]
Short version: I made the shapes by modifying glyphs from common Unicode web fonts and then cobbling together whatever I couldn't find. They're in an Adobe Illustrator file I have on Dropbox, but am leaving out of the repo for now.

I have considered inserting them into a font, but there is one major obstacle: I'd have to choose which character each glyph represents. This was way, way easier with the original glyph set, because those symbols were quickly identifiable. I still don't know where some of the new glyphs come from. I could just assign the glyphs to arbitrary characters, the way icon fonts do, but I don't think that would be an easy font to use.

I think what you really want is [this](https://www.dropbox.com/home/matrix_resurrections_glyphs/draft_new_matrix_glyphs/svg)— a folder of SVG files, where each one contains a single glyph— which I've also got on Dropbox. That way, you have total freedom of their format; you can drop them into [IcoMoon](https://icomoon.io) if you want, or you can use them as images, or you can bake them into a texture.

It made sense a few years ago to keep individual files of the original glyphs in this repo, when I included only one font, but even then I inadvertently broke git on people's Windows machines for naming them like `+.svg`. I'm also more comfortable hosting the MSDF pngs, because they're clearly derived works, in case someone's angry about my glyph recovery techniques for whatever reason.

Either way, I hope this helps. Feel free to also reach out on [Twitter](http://twitter.com/rezmason) or through [my contact page](https://rezmason.net/contact.html) if you want to talk shop. Cheers!

**Comment by tanar185** [comment]
Do you have a version of the Operator code except that it uses the glyphs from Matrix Resurrections?

**Comment by Rezmason** [comment]
That's a good feature request. I'll try adding the ability to specify which glyph set to use in the URL.

**Comment by Rezmason** [comment]
Here you go! 

http://rezmason.github.io/matrix/?version=operator&font=resurrections

The font names are now all listed in the README, too,.

If you have any other requests, please file separate issues for them, so I can track them individually. Thanks for taking an interest in this project!

**Comment by tanar185** [comment]
> I think what you really want is [this](https://www.dropbox.com/home/matrix_resurrections_glyphs/draft_new_matrix_glyphs/svg)— a folder of SVG files, where each one contains a single glyph— which I've also got on Dropbox. That way, you have total freedom of their format; you can drop them into [IcoMoon](https://icomoon.io) if you want, or you can use them as images, or you can bake them into a texture.

The link doesn't work

**Comment by tanar185** [comment]
Also something I noticed is that the new movie confirms that there IS a glyph for the number 6, which is also reversed like the 9 digit
![image](https://user-images.githubusercontent.com/29153122/147395239-09ae9a61-4852-49b8-8bb6-b0ab1156a0f2.png)

**Comment by Rezmason** [comment]
I noticed that too! Also their asterisk is shaped differently than the one in my current glyph sets, and I'll need to investigate that further.
